development:
  host: vismongo
  database: vis_development
  port: 27017

test:
  host: vismongo
  database: vis_test

# set these environment variables on your staging server
staging:
  host: vismongo
  database: vis_staging


# set these environment variables on your prod server
production:
  host: vismongo
  database: vis_production


  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
